version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup run stable rustc --version --verbose
          rustup run stable cargo --version --verbose
          rustup run stable cargo build

workflows:
  version: 2.1
  build:
    jobs:
      - build
