version: 2.1

jobs:
  full_ci_branch:
    machine:
      image: "ubuntu-1604:202004-01"
      docker_layer_caching: true
    resource_class: xlarge
    steps:
      - full_ci:
          cache_target: true

  full_ci_master:
    machine:
      image: "ubuntu-1604:202004-01"
      docker_layer_caching: true
    resource_class: xlarge
    steps:
      - full_ci:
          cache_target: false

workflows:
  build:
    jobs:
      - full_ci_branch:
          filters:
            branches:
              ignore: master
      - full_ci_master:
          filters:
            branches:
              only: master

commands:
  full_ci:
    description: "Run the full CI for Lucet"
    parameters:
      cache_target:
        type: boolean
        description: "If `true`, the target/ directory will be cached between builds"
    steps:
      - checkout_recursively
      - when:
          condition: << parameters.cache_target >>
          steps:
            - restore_cache:
                keys:
                  - target_dir-{{ .Branch }}-{{ checksum "Cargo.lock" }}
                  - target_dir-{{ .Branch }}-
                  - target_dir-
      - build_container
      - make_in_container:
          target: test-full
      - make_in_container:
          target: test-release test-release-executables
      - ensure_sources_unchanged
      - when:
          condition: << parameters.cache_target >>
          steps:
            - save_cache:
                key: target_dir-{{ .Branch }}-{{ checksum "Cargo.lock" }}
                paths:
                  - "target"

  checkout_recursively:
    description: "Check out the git repository, and recursively initialize its submodules"
    steps:
      - checkout
      - run:
          name: "Sync and recursively update submodules"
          command: |
            set -x
            git submodule sync
            git submodule update --init --recursive

  build_container:
    description: "Build the Lucet development/CI Docker image"
    steps:
      - run:
          name: "Build Docker image"
          command: |
            set -x
            docker build -t lucet .

  make_in_container:
    description: Run a make target in the Lucet development/CI Docker image"
    parameters:
      target:
        type: string
    steps:
      - run:
          name: "Run Make target in Docker: << parameters.target >>"
          command: |
            set -x
            docker run --privileged -v `pwd`:/lucet -it lucet /bin/bash -c "make -C /lucet << parameters.target >>"

  ensure_sources_unchanged:
    description: "Make sure that previous steps did not change the source files from git"
    steps:
      - run:
          name: "Ensure sources are unchanged"
          command: |
            set -x
            git diff --exit-code
